export const mockData: TestSchema[] = [
  {
    name: 'Chipotle',
    city: 'Denver',
    state: 'CO',
    phoneNumber: '1234567890',
    attire: 'Casual',
    genres: ['Fast casual', 'Tex Mex'],
    mustTry: 'Carne asada',
  },
  {
    name: 'Cafe Mexicali',
    city: 'Fort Collins',
    state: 'CO',
    phoneNumber: '0987654321',
    attire: 'Casual',
    genres: ['Fast casual', 'Tex Mex'],
    mustTry: 'Sweet pork with creamy habenero sauce',
  },
  {
    name: 'Sushi Den',
    city: 'Denver',
    state: 'CO',
    phoneNumber: '0987654321',
    attire: 'Business casual',
    genres: ['Sushi', 'Japanese'],
    mustTry: 'Everything',
  },
  {
    name: "Lucile's",
    city: 'Denver',
    state: 'CO',
    phoneNumber: '0987654321',
    attire: 'Casual',
    genres: ['Breakfast', 'Brunch', 'Lunch', 'Creole'],
    mustTry: 'Eggs Pontchartrain',
  },
  {
    name: 'Larkburger',
    city: 'Denver',
    state: 'CO',
    phoneNumber: '1234567890',
    attire: 'Casual',
    genres: ['American', 'Burger joint', 'Fast casual'],
    mustTry: 'Portabello mushroom burger with onion rings',
  },
  {
    name: 'Denver Biscuit Company',
    city: 'Denver',
    state: 'CO',
    phoneNumber: '0987654321',
    attire: 'Casual',
    genres: ['Breakfast', 'Brunch'],
    mustTry:
      'Almond Tres Leches French Toast (with peppered bacon on the side)',
  },
  {
    name: 'Denver Biscuit Company',
    city: 'Denver',
    state: 'CO',
    phoneNumber: '0987654321',
    attire: 'Casual',
    genres: ['Breakfast', 'Brunch'],
    mustTry: 'The Franklin',
  },
]
