import { Values } from '../../../_components/Table/Table.d'

// By default All is selected, so all values are set to true
export const GENRES: Values = {
  American: true,
  Asian: true,
  Belgian: true,
  bistro: true,
  British: true,
  cafe: true,
  coffee: true,
  contemporary: true,
  continental: true,
  European: true,
  French: true,
  fusion: true,
  grill: true,
  Hawaiian: true,
  international: true,
  Irish: true,
  Italian: true,
  Japanese: true,
  oysters: true,
  'Pacific Rim': true,
  Polynesian: true,
  sandwiches: true,
  seafood: true,
  steak: true,
  sushi: true,
  traditional: true,
  vegetarian: true,
  Vietnamese: true,
}
